import { Router } from "express";
import { ArticlesRepository } from "../repositories/articlesRepository.js";
import { ArticlesService } from "../services/articlesService.js";
import { ShareController } from "../controllers/shareController.js";
const shareRouter = Router();
const articleRepo = new ArticlesRepository();
const articleService = new ArticlesService(articleRepo);
const shareCtrl = new ShareController(articleService);
shareRouter.get("/share/:articleId", shareCtrl.sharePage);
export default shareRouter;
