// Generated by scripts/build-locales.mjs. Do not edit.
export const supportedLocales = ["en", "ja"] as const;
export type SupportedLocale = (typeof supportedLocales)[number];

export const localeLoaders = {
  "en": () => import("./generated/en"),
  "ja": () => import("./generated/ja"),
} as const;
